---
- job:
    name: distroinfo-base
    parent: tox
    abstract: true
    pre-run: playbooks/base.yaml

- job:
    name: distroinfo-base-py2
    parent: distroinfo-base
    abstract: true
    nodeset:
      nodes:
        - name: test-node
          label: centos-oci

- job:
    name: distroinfo-base-py3
    parent: distroinfo-base
    abstract: true
    nodeset:
      nodes:
        - name: test-node
          label: f27-oci

- job:
    name: distroinfo-py2-centos-7
    parent: distroinfo-base-py2
    description: distroinfo tests on python2
    vars:
      tox_envlist: py2-unit

- job:
    name: distroinfo-py3-fedora-27
    parent: distroinfo-base-py3
    description: distroinfo tests on python3
    vars:
      tox_envlist: py3-unit

- job:
    name: distroinfo-integration
    parent: distroinfo-base-py2
    description: distroinfo integration tests with rdoinfo
    vars:
      tox_envlist: integration

- job:
    name: distroinfo-codestyle
    parent: distroinfo-base-py2
    description: distroinfo code style checks
    vars:
      tox_envlist: pycodestyle

- job:
    name: distroinfo-dlrn-master
    parent: dlrn-base
    description: distroinfo integration tests with DLRN master
    run: playbooks/dlrn-master.yaml
    required-projects:
      - DLRN

- project:
    name: distroinfo
    check:
      jobs:
        - distroinfo-py2-centos-7
        - distroinfo-py3-fedora-27
        - distroinfo-integration
        - distroinfo-codestyle
        - distroinfo-dlrn-master
    gate:
      jobs:
        - distroinfo-py2-centos-7
        - distroinfo-py3-fedora-27
        - distroinfo-integration
        - distroinfo-codestyle
        - distroinfo-dlrn-master
    release:
      jobs:
        - upload-pypi
